name: emprega_ribamar
description: Um novo projeto Flutter para São José de Ribamar.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - lib/assets/imagens/logo-riba.png
    - lib/assets/imagens/joao.jpeg
